steps:
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.2.0:
        files: hooks/**

  - label: ":sparkles:"
    plugins:
      plugin-linter#v3.0.0:
        id: docker

  - label: ":docker: :hammer:"
    plugins:
      docker-compose#v3.9.0:
        run: tests

  - wait
  - label: run the plugin
    command: "echo hello world"
    plugins:
      ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO}#${BUILDKITE_COMMIT}:
        image: ubuntu:20.04
