steps:
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.0.1:
        files: hooks/**

  - label: ":sparkles:"
    plugins:
      plugin-linter#v2.0.0:
        id: docker

  - label: ":docker: :hammer:"
    plugins:
      docker-compose#v2.4.1:
        run: tests
